# Site Settings
lang: en
title: CMU Biorobotics
tagline: Biorobotics lab website
email: choset@andrew.cmu.edu
description: >
  The website for the Carnegie Mellon Biorobitcs lab
# baseurl: "/lab_website"
baseurl: ""
url: "https://biorobotics.org/"
permalink: pretty
#favicon: /path/to/favicon.png
# gh_sponsor: chrisrhymes
#hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: 


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _prose.yml

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
      hide_hero: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Biorobotics"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true
      permalink: /posts/:year/:month/:day/:title/
      hide_hero: true
      summary: |

markdown: kramdown
highlighter: rouge

footer_menu: footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
