<?php include $_SERVER['DOCUMENT_ROOT'].'/phpincludes/header.php'; ?>

<!-- Basic Page Needs - Edit keywords and page title here
============================= -->

	<title>Robotic Internect of Things Research - Biorobotics</title>
	<meta name="Keywords" content="Robotic Internect of Things, Robotics,
	internet, Carnegie Mellon University, robotics">
	<meta name="description" content ="Robotic Internect of Things Research - Carnegie Mellon Biorobotics" />

	<!-- Banner and Menu - Do not change
============================= -->
<?php include $_SERVER['DOCUMENT_ROOT']."/phpincludes/banner.php";?>

<!-- Content - Add content for your page here
============================= -->
    
	<div class="row">
		<div class="six columns">
			<h3><b>Robotic Internect of Things </h3> 
			<p>
				 With the growing needs of collecting, storing, and processing data generated by advanced robotic systems, we proposed a generic data center and server architecture for next-generation connected intelligent mobile robots, mobile manipulators and factory automation infrastructures. 

				 <br>

				The goal of this proposed system is to address three main challenges when integrating large-scale robotic fleet to existing or future automation factory floors. To begin with, the lack of a centralized and intuitive data visualization interface does not satisfy the growing number of connected devices in the automation networks. For example, current state of art visualization tools widely used in robotics communities is still limited to command line terminals and single machine based graphical interfaces, which is primitive and inefficient to display information generated by thousands or even millions of connected robotic systems in the production line. Furthermore, there are no convenient methods to perform fleet management tasks among the robotic device networks, such as pushing commands within subgroups, mass software update deployments, selective reset, and recovering process. Lastly, although there are some commercial solutions to solve above problems, they tend to not provide rich research purposed software interfaces, and less upgradable and scalable due to the nature of using proprietary software architectures. To solve this problem, our solution will provide an intuitive web-based data visualization front end, pairs with an operation centric robot fleet management graphical interface, while also provide rich research and statistic software interface for advanced users. 

				<br>

				This data center and server consist of four parts. First, the edge nodes create a secured connection between each robot system and local data network, while physically isolating the robot internal system from the local data network using custom defined data bus and communication protocol for maximized cybersecurity. Second, in-factory data hubs acting as the gateway device between the local data network and cloud-based remote network, while also can be promoted to local data center and server when external internet been disconnected due to internet failure or intentional separation from the external network. Third, a cloud-based database will be located in remote data centers, such as Amazon DynamoDB or S3 for temporary or long term data storage. Lastly, a robotic data server will be used for providing event-based processing, data-driven machine learning, simulation and visualization support interfaces.

			</p>
		</div>
		<div  class="six columns">
			<img src="images/RIOT/fig1.png" alt="RIOTF1" width="100%;" style="padding-left:2rem; padding-top:10rem;">
			<img src="images/RIOT/fig2.png" alt="RIOTF2" width="100%;" style="padding-left:2rem; padding-top:13rem;">
		</div>
	</div>


	
	
<!-- Gallery - include if page has gallery elements
============================= -->
<?php include $_SERVER['DOCUMENT_ROOT']."/phpincludes/gallery.php";?>

<!-- Footer - Do not change
============================= -->
<?php include $_SERVER['DOCUMENT_ROOT']."/phpincludes/footer.php";?>